# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: VDO.Ninja - Guide
description: >
  Step-by-step guides for VDO.Ninja - free browser-based video streaming
  for OBS, live production, and remote collaboration.
url: "https://guides.vdo.ninja" # the base hostname & protocol for your site

# Contact settings
email: steve@seguin.email
github_username:  steveseguin

# Build settings
markdowm: kramdown

kramdown:
  input:      GFM
  auto_ids:   false

sass:
  style: compact

exclude: ["README.md", "LICENSE.md", "screenshot.png"]
